name: Build DLL Mod

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Solution
      run: |
        msbuild Source/DllMods.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GenerationsParameterEditor
        path: |
          Source/db/GenerationsParameterEditor.dll
          Source/Release/GenerationsParameterEditor.dll